/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/error-message/404.vue')['default']
    DraggableDialog: typeof import('./src/components/DraggableDialog.vue')['default']
    MessageApi: typeof import('./src/components/message-api/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NResult: typeof import('naive-ui')['NResult']
    NSplit: typeof import('naive-ui')['NSplit']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
